[package]
name = "icy_draw"
version = "0.1.0"
edition = "2021"
description = "An ansi drawing tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20.0"
egui_extras = { version="0.20.0", features = ["svg"] }
egui_glow = "0.20.0"
glow = "0.11.2"
egui_dock = { git="https://github.com/Adanos020/egui_dock.git" }

icy_engine = { path = "../icy_engine" }
walkdir = "2"
serde = { version = "1", features = ["derive"], optional = true }
lazy_static = "1.4.0"
rfd = "0.10.0"

i18n-embed = { version = "0.13.4", features = ["fluent-system", "desktop-requester"]} 
i18n-embed-fl = "0.6.4"
rust-embed = "6.4.2"
once_cell = "1.16.0"

[features]
default = []
